baseURL = "http://chetaldrich.com/"
languageCode = "en-us"
title = "Chet Aldrich"

[permalinks]
  blog = "/:filename/"

[taxonomies]
  tag = "tags"

[params]
  dateFormat = "Jan 2, 2006"
  homeText = "You just made a Hugo blog from scratch."
