version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - cci-demo-haskell-v1-{{ checksum "stack.yaml" }}
      - run: stack setup
      - run: stack update
      - run: stack install
      - save_cache:
          name: Cache Dependencies
          key: cci-demo-haskell-v1-{{ checksum "stack.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
  test:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - cci-demo-haskell-v1-{{ checksum "stack.yaml" }}
      - run: stack build
      - run: stack
      - run: git submodule init
      - run: git submodule update
      - run: cd _site/ && git checkout master
      - run: stack exec site build

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
