version: 2.1
jobs:
  checkout_code:
    docker:
      - image: fpco/stack-build:lts
    working_directory: ~/chetaldrich.github.io/
    steps:
      - checkout
      - save_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/chetaldrich.github.io
  build:
    docker:
      - image: fpco/stack-build:lts
    working_directory: ~/chetaldrich.github.io/
    steps:
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: stack-deps-{{ checksum "stack.yaml" }}
      - run: stack setup
      - run: stack update
      - run: stack install
      - save_cache:
          key: stack-deps-{{ checksum "stack.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
  test:
    docker:
      - image: fpco/stack-build:lts
    working_directory: ~/chetaldrich.github.io/
    steps:
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: stack-deps-{{ checksum "stack.yaml" }}
      - run: stack build
      - run: git submodule init
      - run: git submodule update
      - run: cd _site/ && git checkout master
      - run: stack exec site build

workflows:
  version: 2
  build-and-test:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - test:
          requires:
            - build
